CREATE TABLE IF NOT EXISTS KUNDEN (
    KUNDEN_ID     INT NOT NULL,
    GEBURTSTAG    DATE NOT NULL,
    -- other attributes
    PRIMARY KEY (KUNDEN_ID, GEBURTSTAG)
) PARTITION BY RANGE (YEAR(GEBURTSTAG)) (
    PARTITION p1 VALUES LESS THAN (1955),
    PARTITION p2 VALUES LESS THAN (1960),
    -- other partitions
    PARTITION p15 VALUES LESS THAN (2025),
    PARTITION pmax VALUES LESS THAN MAXVALUE
);