name: Benchmark Workflow
on:
  push:
    paths:
      - 'Projects/**'
      - ...
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [high-count, low-count, b-tree-query-differences, selectivity-change, hash-query-differences, join-type, null-check, int-char, data-size]
    env:
      OTHER_ENVIRONMENT_VARIABLES
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Load configuration from JSON
        run: # removed the definition and export of variables for simplicity reasons
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sysbench
          python -m pip install --upgrade pip
          pip install pandas matplotlib
      - name: Start MySQL container
        run: |
          docker run --name mysql-${{ matrix.test-type }} -d \
            -e MYSQL_ROOT_PASSWORD=$DB_PASS \
            -e MYSQL_DATABASE=$DB_NAME \
            -p $DB_PORT:3306 mysql:8.0
          until docker exec mysql-${{ matrix.test-type }} mysqladmin --user=root --password=$DB_PASS --host=127.0.0.1 --port=$DB_PORT ping --silent; do sleep 1; done
          echo "MySQL is ready!"
      - name: Run sysbench script
        run: |
          chmod +x Tools/sysbench_script.sh
          Tools/sysbench_script.sh \
            -out ${{ env.output_dir }} \
            -var '${{ env.var }}' \
            -scripts:$(echo "${{ env.dirs_string }}" | sed 's/ / /g')
      - name: Stop MySQL container
        run: |
          docker stop mysql-${{ matrix.test-type }}
          docker rm mysql-${{ matrix.test-type }}  
      - name: Upload all
        uses: actions/upload-artifact@v3
        with:
          name: combined-output
          path: Output