SELECT YEAR(B.BESTELLDATUM) AS Jahr, K.LAND AS Land, SUM(B.UMSATZ) AS Gesamtumsatz
FROM KUNDEN K
         JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN
GROUP BY YEAR(B.BESTELLDATUM), K.LAND
ORDER BY Jahr ASC, Gesamtumsatz DESC;