SELECT YEAR (B.BESTELLDATUM) AS Jahr, K.STADT, SUM (B.UMSATZ) AS Gesamtumsatz
FROM KUNDEN K
    JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN
GROUP BY YEAR (B.BESTELLDATUM), K.STADT
ORDER BY Jahr DESC, Gesamtumsatz DESC;