CREATE MATERIALIZED VIEW UmsatzProJahrStadt AS
SELECT
    EXTRACT(YEAR FROM B.BESTELLDATUM) AS Jahr,
    K.STADT AS Stadt,
    SUM(B.UMSATZ) AS Gesamtumsatz
FROM KUNDEN K
         JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN
GROUP BY EXTRACT(YEAR FROM B.BESTELLDATUM), K.STADT;