CREATE MATERIALIZED VIEW UmsatzProJahrLand AS
SELECT
    EXTRACT(YEAR FROM B.BESTELLDATUM) AS Jahr,
    K.LAND AS Land,
    SUM(B.UMSATZ) AS Gesamtumsatz
FROM KUNDEN K
     JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN
GROUP BY EXTRACT(YEAR FROM B.BESTELLDATUM), K.LAND;