CREATE TRIGGER UPDATE_BESTELLUNG_MAT_OVERVIEW_AFTER_INSERT
AFTER INSERT ON BESTELLUNG
FOR EACH ROW
BEGIN
    DECLARE v_land VARCHAR(255);
    DECLARE v_jahr INT;
    SELECT LAND INTO v_land FROM KUNDEN WHERE KUNDEN_ID = NEW.FK_KUNDEN;
    SELECT EXTRACT(YEAR FROM NEW.BESTELLDATUM) INTO v_jahr;
    IF EXISTS (
        SELECT 1 FROM KUNDEN_MAT_OVERVIEW WHERE LAND = v_land AND JAHR = v_jahr
    ) THEN
        UPDATE KUNDEN_MAT_OVERVIEW
        SET GESAMTUMSATZ = GESAMTUMSATZ + NEW.UMSATZ
        WHERE LAND = v_land AND JAHR = v_jahr;
    ELSE
        INSERT INTO KUNDEN_MAT_OVERVIEW (JAHR, LAND, GESAMTUMSATZ)
        VALUES (v_jahr, v_land, NEW.UMSATZ);
    END IF;
END;