CREATE TABLE IF NOT EXISTS KUNDEN (
    KUNDEN_ID     INT PRIMARY KEY,
    NAME          VARCHAR(255),
    GEBURTSTAG    DATE,
    ADRESSE       VARCHAR(255),
    STADT         VARCHAR(100),
    POSTLEITZAHL  VARCHAR(10),
    LAND          VARCHAR(100),
    EMAIL         VARCHAR(255) UNIQUE,
    TELEFONNUMMER VARCHAR(20)
);
DROP TABLE KUNDEN;
DROP VIEW KUNDEN_OVERVIEW;

CREATE INDEX idx_stadt ON KUNDEN(STADT);
CREATE INDEX idx_postleitzahl ON KUNDEN(POSTLEITZAHL);
CREATE INDEX idx_geburtstag ON KUNDEN(GEBURTSTAG);

DROP INDEX idx_stadt ON KUNDEN;
DROP INDEX idx_postleitzahl ON KUNDEN;
DROP INDEX idx_geburtstag ON KUNDEN;
DROP INDEX idx_name ON KUNDEN;

CREATE INDEX combined_index ON KUNDEN(NAME, VORNAME, GEBURTSTAG);
DROP INDEX combined_index ON KUNDEN;
CREATE INDEX combined_index
    ON KUNDEN (NAME, VORNAME, GEBURTSTAG);
USING HASH;

SELECT * FROM KUNDEN;
SELECT * FROM KUNDEN WHERE CAST(SUBSTRING(STADT, 6) AS UNSIGNED) > 9;
SELECT COUNT(*) as count  FROM KUNDEN;