-- Data Types
CREATE TABLE KUNDEN (
    KUNDEN_ID     INT PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    GEBURTSTAG    DATE NOT NULL,
    ADRESSE       VARCHAR(255) NOT NULL,
    STADT         VARCHAR(100) NOT NULL,
    POSTLEITZAHL  VARCHAR(10) NOT NULL,
    LAND          VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(255) UNIQUE NOT NULL,
    TELEFONNUMMER VARCHAR(20) NOT NULL
);

